/************************************************************
 * File: CPU_build.h                    Created: 2026/08/15 *
 *                                    Last mod.: 2026/08/15 *
 *                                                          *
 * Desc: Build settings the golden values depend upon.      *
 *                                                          *
 * MIT license             Copyright (c) David William Bull *
 ************************************************************/
#pragma once

#include "typedefs.h"

//--- Target architecture ---//
// PITC is x64 only. The kernels use _mm_set1_epi64x and the 512-bit intrinsics, none of which exist on x86,
// and the topology, affinity and arena code is written against 64-bit masks throughout. The Win32
// configurations that used to sit in CPU.vcxproj carried none of the settings the x64 ones do -- no
// LanguageStandard, no per-file ISA or optimisation overrides -- so selecting one produced a cascade of
// errors and, had it linked, an executable named CPU.exe running arithmetic the golden values do not
// describe. They are gone (ISSUES.MD H7); this rejects a build configured for x86 by any other route

#if !defined(_M_X64) && !defined(_M_AMD64) && !defined(__x86_64__)
   #error "PITC targets x64 only. See CPU.vcxproj and ISSUES.MD H7."
#endif
//--- Target architecture ---//

//--- Floating-point model ---//
// Every golden value in "cpu.values" is the output of a chain of divides and square roots, so the model the
// kernels are compiled under is part of the definition of a correct result. /fp:fast reassociates, and
// /fp:precise lets the compiler contract a*b+c into a single FMA whose one rounding differs from the two
// the source performs -- JobFPU ends each outer iteration with exactly that shape. A file generated by a
// build using one model would then be graded against silicon running another, and the difference reported
// to the user as a CPU fault. The model is therefore pinned by every configuration in CPU.vcxproj, and
// required here as well, so that a build made outside the project file cannot quietly inherit another one

#if defined(_MSC_VER) && !defined(__clang__) && !defined(_M_FP_STRICT)
   #error "PITC must be compiled with /fp:strict. See CPU.vcxproj <FloatingPointModel> and ISSUES.MD H2."
#endif

// Identifies the model in the "cpu.values" header, so a file written by a build using another one is
// reported as a stale file rather than as a hardware failure. /fp:except is deliberately not represented:
// it decides whether an exception is raised, not what a result is
#if defined(_M_FP_STRICT)
   constexpr cui32 VALUES_FP_MODEL = 1;
#elif defined(_M_FP_PRECISE)
   constexpr cui32 VALUES_FP_MODEL = 2;
#elif defined(_M_FP_FAST)
   constexpr cui32 VALUES_FP_MODEL = 3;
#else
   constexpr cui32 VALUES_FP_MODEL = 0;
#endif

// _M_FP_CONTRACT is only defined by the VS 2022 toolsets, but its absence on an older one is
// indistinguishable from contraction being disabled -- which is what /fp:strict already guarantees
#ifdef _M_FP_CONTRACT
   constexpr cui32 VALUES_FP_FLAGS = VALUES_FP_MODEL | 0x010;
#else
   constexpr cui32 VALUES_FP_FLAGS = VALUES_FP_MODEL;
#endif
//--- Floating-point model ---//
