/*
 * File: CPU_build.h
 * Version: v1.0.2
 * Owner: David William Bull
 * Created: 2026-08-15
 * Last Modified: 2026-08-16
 * Description: Build guards and the floating-point identity the golden values depend upon: x64 only, MSVC only, /fp:strict only.
 * To Do: 1) Generate and validate the golden values under clang-cl, then narrow the refusal below to a mode check (ISSUES.MD H1)
 *        2) State an explicit toolset floor: on a pre-VS2022 toolset an absent _M_FP_CONTRACT reads as contraction being off
 * Dependencies: typedefs.h
 * ISA: Scalar
 * Thread-safety: N/A
 * Reviewers: David William Bull
 * License: MIT  Copyright: David William Bull
 */
#pragma once

#include "typedefs.h"

//--- Target architecture ---//
#if !defined(_M_X64) && !defined(_M_AMD64) && !defined(__x86_64__)
   #error "PITC targets x64 only. See CPU.vcxproj and ISSUES.MD H7."
#endif
//--- Target architecture ---//

//--- Floating-point model ---//
// Every golden value in "cpu.values" is the output of a chain of divides and square roots, so the model the
// kernels are compiled under is part of the definition of a correct result. /fp:fast reassociates, and
// /fp:precise lets the compiler contract a*b+c into a single FMA whose one rounding differs from the two
// the source performs -- JobFPU ends each outer iteration with exactly that shape. A file generated by a
// build using one model would then be graded against silicon running another, and the difference reported
// to the user as a CPU fault. The model is therefore pinned by every configuration in CPU.vcxproj, and
// required here as well, so that a build made outside the project file cannot quietly inherit another one
#if defined(__clang__)
   #error "PITC has no validated clang build: its floating-point model cannot be checked. See ISSUES.MD H1."
#elif !defined(_MSC_VER)
   #error "PITC builds with MSVC only: no other compiler here states its floating-point model. See ISSUES.MD H1."
#elif !defined(_M_FP_STRICT)
   #error "PITC must be compiled with /fp:strict. See CPU.vcxproj <FloatingPointModel> and ISSUES.MD H2."
#endif

// Identifies the model in the "cpu.values" header, so a file written by a build using another one is
// reported as a stale file rather than as a hardware failure. /fp:except is deliberately not represented:
// it decides whether an exception is raised, not what a result is. The guard above admits only a toolchain
// that names its model, so the final arm is unreachable and 0 can no longer stand for "some model this
// build cannot identify"
#if defined(_M_FP_STRICT)
   constexpr cui32 VALUES_FP_MODEL = 1;
#elif defined(_M_FP_PRECISE)
   constexpr cui32 VALUES_FP_MODEL = 2;
#elif defined(_M_FP_FAST)
   constexpr cui32 VALUES_FP_MODEL = 3;
#else
   constexpr cui32 VALUES_FP_MODEL = 0;
#endif

// _M_FP_CONTRACT is only defined by the VS 2022 toolsets, but its absence on an older one is
// indistinguishable from contraction being disabled -- which is what /fp:strict already guarantees
#ifdef _M_FP_CONTRACT
   constexpr cui32 VALUES_FP_FLAGS = VALUES_FP_MODEL | 0x010;
#else
   constexpr cui32 VALUES_FP_FLAGS = VALUES_FP_MODEL;
#endif
//--- Floating-point model ---//
