/************************************************************
 * File: CPU_build.h                    Created: 2026/08/15 *
 *                                    Last mod.: 2026/08/15 *
 *                                                          *
 * Desc: Build settings the golden values depend upon.      *
 *                                                          *
 * MIT license             Copyright (c) David William Bull *
 ************************************************************/
#pragma once

#include "typedefs.h"

//--- Target architecture ---//
// PITC is x64 only. The kernels use _mm_set1_epi64x and the 512-bit intrinsics, none of which exist on x86,
// and the topology, affinity and arena code is written against 64-bit masks throughout. The Win32
// configurations that used to sit in CPU.vcxproj carried none of the settings the x64 ones do -- no
// LanguageStandard, no per-file ISA or optimisation overrides -- so selecting one produced a cascade of
// errors and, had it linked, an executable named CPU.exe running arithmetic the golden values do not
// describe. They are gone (ISSUES.MD H7); this rejects a build configured for x86 by any other route

#if !defined(_M_X64) && !defined(_M_AMD64) && !defined(__x86_64__)
   #error "PITC targets x64 only. See CPU.vcxproj and ISSUES.MD H7."
#endif
//--- Target architecture ---//

//--- Floating-point model ---//
// Every golden value in "cpu.values" is the output of a chain of divides and square roots, so the model the
// kernels are compiled under is part of the definition of a correct result. /fp:fast reassociates, and
// /fp:precise lets the compiler contract a*b+c into a single FMA whose one rounding differs from the two
// the source performs -- JobFPU ends each outer iteration with exactly that shape. A file generated by a
// build using one model would then be graded against silicon running another, and the difference reported
// to the user as a CPU fault. The model is therefore pinned by every configuration in CPU.vcxproj, and
// required here as well, so that a build made outside the project file cannot quietly inherit another one

// The exemption this guard used to grant -- '&& !defined(__clang__)' -- excused the one route it exists to
// police. clang-cl defines _MSC_VER and __clang__ alike, and a build made outside CPU.vcxproj is exactly the
// case the guard is written for, so the toolchain most likely to reach here unconfigured was the toolchain it
// let through. clang publishes none of the _M_FP_* macros either, so VALUES_FP_MODEL below was 0 for every
// clang floating-point mode: two clang-cl builds made under /fp:fast and /fp:precise shared a buildID, would
// have exchanged "cpu.values" files whose arithmetic rounds differently, and the difference would have
// reached the user as a CPU fault -- the class of failure the buildID exists to prevent. clang-cl can model
// /fp:strict, but it defines no macro that says it did, so there is nothing here to test against; the golden
// values have never been generated or validated under it, and it is refused until they are. A toolchain that
// is neither MSVC nor clang arrives at the same dead end from the other side, VALUES_FP_MODEL having no way
// to name the model such a build was made with (ISSUES.MD H1)

#if defined(__clang__)
   #error "PITC has no validated clang build: its floating-point model cannot be checked. See ISSUES.MD H1."
#elif !defined(_MSC_VER)
   #error "PITC builds with MSVC only: no other compiler here states its floating-point model. See ISSUES.MD H1."
#elif !defined(_M_FP_STRICT)
   #error "PITC must be compiled with /fp:strict. See CPU.vcxproj <FloatingPointModel> and ISSUES.MD H2."
#endif

// Identifies the model in the "cpu.values" header, so a file written by a build using another one is
// reported as a stale file rather than as a hardware failure. /fp:except is deliberately not represented:
// it decides whether an exception is raised, not what a result is. The guard above admits only a toolchain
// that names its model, so the final arm is unreachable and 0 can no longer stand for "some model this
// build cannot identify" -- which is what made it a value two different builds could share (H1)
#if defined(_M_FP_STRICT)
   constexpr cui32 VALUES_FP_MODEL = 1;
#elif defined(_M_FP_PRECISE)
   constexpr cui32 VALUES_FP_MODEL = 2;
#elif defined(_M_FP_FAST)
   constexpr cui32 VALUES_FP_MODEL = 3;
#else
   constexpr cui32 VALUES_FP_MODEL = 0;
#endif

// _M_FP_CONTRACT is only defined by the VS 2022 toolsets, but its absence on an older one is
// indistinguishable from contraction being disabled -- which is what /fp:strict already guarantees
#ifdef _M_FP_CONTRACT
   constexpr cui32 VALUES_FP_FLAGS = VALUES_FP_MODEL | 0x010;
#else
   constexpr cui32 VALUES_FP_FLAGS = VALUES_FP_MODEL;
#endif
//--- Floating-point model ---//
